import QtQuick 2.0
IGuiPage
{
	id: q16777219
	objId: 16777219
	x: 0
	y: 0
	width: 480
	height: 272
	IGuiContainer
	{
		id: q369098752
		objId: 369098752
		x: 0
		y: 0
		width: 480
		height: 272
	}
	IGuiTextField
	{
		id: q268435549
		objId: 268435549
		x: 120
		y: 30
		width: 120
		height: 25
		qm_FillRectWidth: 120
		qm_FillRectHeight: 25
		qm_FontFamilyName: "Tahoma"
		qm_FontSize: 17
		qm_BorderCornerRadius: 0
		qm_BorderWidth: 0
		qm_BorderColor: "#ff000000"
		qm_ImageID: 33
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignTop
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435548
		objId: 268435548
		x: 0
		y: 0
		width: 480
		height: 25
		qm_FillRectWidth: 480
		qm_FillRectHeight: 25
		qm_FontFamilyName: "Tahoma"
		qm_FontSize: 17
		qm_BorderCornerRadius: 0
		qm_BorderWidth: 1
		qm_BorderColor: "#ff000000"
		qm_ImageID: 17
		qm_TileTop: 2
		qm_TileBottom: 2
		qm_TileRight: 2
		qm_TileLeft: 2
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignTop
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435547
		objId: 268435547
		x: 10
		y: 55
		width: 25
		height: 30
		qm_FillRectWidth: 25
		qm_FillRectHeight: 30
		qm_FontFamilyName: "Tahoma"
		qm_FontSize: 17
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435546
		objId: 268435546
		x: 10
		y: 100
		width: 25
		height: 30
		qm_FillRectWidth: 25
		qm_FillRectHeight: 30
		qm_FontFamilyName: "Tahoma"
		qm_FontSize: 17
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435545
		objId: 268435545
		x: 10
		y: 145
		width: 25
		height: 30
		qm_FillRectWidth: 25
		qm_FillRectHeight: 30
		qm_FontFamilyName: "Tahoma"
		qm_FontSize: 17
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435544
		objId: 268435544
		x: 10
		y: 190
		width: 25
		height: 30
		qm_FillRectWidth: 25
		qm_FillRectHeight: 30
		qm_FontFamilyName: "Tahoma"
		qm_FontSize: 17
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435543
		objId: 268435543
		x: 325
		y: 30
		width: 80
		height: 20
		qm_FillRectWidth: 80
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontSize: 16
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435542
		objId: 268435542
		x: 405
		y: 30
		width: 70
		height: 20
		qm_FillRectWidth: 70
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontSize: 16
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435541
		objId: 268435541
		x: 2
		y: 30
		width: 45
		height: 25
		qm_FillRectWidth: 45
		qm_FillRectHeight: 25
		qm_FontFamilyName: "Tahoma"
		qm_FontSize: 17
		qm_BorderCornerRadius: 0
		qm_BorderWidth: 0
		qm_BorderColor: "#ff000000"
		qm_ImageID: 33
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignTop
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiIOField
	{
		id: q33554466
		objId: 33554466
		x: 50
		y: 55
		width: 275
		height: 30
		qm_FillRectWidth: 274
		qm_FillRectHeight: 29
		qm_FontSize: 16
		qm_FontFamilyName: "Tahoma"
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 24
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ffffffff"
		qm_FocusWidth: 0
		qm_FocusColor: "#00000000"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_passwordMode: false
		qm_FontRendringTpe:1
	}
	IGuiIOField
	{
		id: q33554465
		objId: 33554465
		x: 50
		y: 100
		width: 275
		height: 30
		qm_FillRectWidth: 274
		qm_FillRectHeight: 29
		qm_FontSize: 16
		qm_FontFamilyName: "Tahoma"
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 24
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ffffffff"
		qm_FocusWidth: 0
		qm_FocusColor: "#00000000"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
		qm_passwordMode: false
		qm_FontRendringTpe:1
	}
	IGuiIOField
	{
		id: q33554464
		objId: 33554464
		x: 50
		y: 145
		width: 275
		height: 30
		qm_FillRectWidth: 274
		qm_FillRectHeight: 29
		qm_FontSize: 16
		qm_FontFamilyName: "Tahoma"
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 24
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ffffffff"
		qm_FocusWidth: 0
		qm_FocusColor: "#00000000"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
		qm_passwordMode: false
		qm_FontRendringTpe:1
	}
	IGuiIOField
	{
		id: q33554463
		objId: 33554463
		x: 50
		y: 190
		width: 275
		height: 30
		qm_FillRectWidth: 274
		qm_FillRectHeight: 29
		qm_FontSize: 16
		qm_FontFamilyName: "Tahoma"
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 24
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ffffffff"
		qm_FocusWidth: 0
		qm_FocusColor: "#00000000"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
		qm_passwordMode: false
		qm_FontRendringTpe:1
	}
	IGuiButton
	{
		id: q486539311
		objId: 486539311
		x: 425
		y: 240
		width: 55
		height: 32
		qm_FillRectWidth: 54
		qm_FillRectHeight: 31
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 22
		qm_TileTop: 15
		qm_TileBottom: 15
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ffffffff"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_FontSize: 13
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
	}
	IGuiButton
	{
		id: q486539310
		objId: 486539310
		x: 0
		y: 240
		width: 55
		height: 32
		qm_FillRectWidth: 54
		qm_FillRectHeight: 31
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 22
		qm_TileTop: 15
		qm_TileBottom: 15
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ffffffff"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_FontSize: 13
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321575
		objId: 352321575
		x: 345
		y: 60
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff5a596b"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffff0000"
		qm_SliderRectOnFillColor: "#ff00ff00"
		qm_FontSize: 1
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: false
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321574
		objId: 352321574
		x: 345
		y: 105
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff5a596b"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffff0000"
		qm_SliderRectOnFillColor: "#ff00ff00"
		qm_FontSize: 1
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: false
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321573
		objId: 352321573
		x: 345
		y: 150
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff5a596b"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffff0000"
		qm_SliderRectOnFillColor: "#ff00ff00"
		qm_FontSize: 1
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: false
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321572
		objId: 352321572
		x: 345
		y: 195
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff5a596b"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffff0000"
		qm_SliderRectOnFillColor: "#ff00ff00"
		qm_FontSize: 1
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: false
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321571
		objId: 352321571
		x: 420
		y: 60
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff5a596b"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffff0000"
		qm_SliderRectOnFillColor: "#ff00ff00"
		qm_FontSize: 1
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: false
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321570
		objId: 352321570
		x: 420
		y: 105
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff5a596b"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffff0000"
		qm_SliderRectOnFillColor: "#ff00ff00"
		qm_FontSize: 1
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: false
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321569
		objId: 352321569
		x: 420
		y: 150
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff5a596b"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffff0000"
		qm_SliderRectOnFillColor: "#ff00ff00"
		qm_FontSize: 1
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: false
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321568
		objId: 352321568
		x: 420
		y: 195
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff5a596b"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffff0000"
		qm_SliderRectOnFillColor: "#ff00ff00"
		qm_FontSize: 1
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: false
		qm_SwitchOnValue: 1
	}
}
