import QtQuick 2.0
IGuiPage
{
	id: q16777217
	objId: 16777217
	x: 0
	y: 0
	width: 480
	height: 272
	IGuiContainer
	{
		id: q369098752
		objId: 369098752
		x: 0
		y: 0
		width: 480
		height: 272
	}
	IGuiTextField
	{
		id: q268435507
		objId: 268435507
		x: 0
		y: 130
		width: 480
		height: 105
		qm_FillRectWidth: 479
		qm_FillRectHeight: 104
		qm_FontFamilyName: "Tahoma"
		qm_FontSize: 15
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 1
		qm_BorderColor: "#ff000000"
		qm_ImageID: 20
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignTop
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435506
		objId: 268435506
		x: 15
		y: 30
		width: 140
		height: 20
		qm_FillRectWidth: 140
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435505
		objId: 268435505
		x: 205
		y: 30
		width: 30
		height: 20
		qm_FillRectWidth: 30
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435504
		objId: 268435504
		x: 15
		y: 55
		width: 140
		height: 20
		qm_FillRectWidth: 140
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435503
		objId: 268435503
		x: 15
		y: 80
		width: 140
		height: 20
		qm_FillRectWidth: 140
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435502
		objId: 268435502
		x: 15
		y: 105
		width: 140
		height: 20
		qm_FillRectWidth: 140
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435501
		objId: 268435501
		x: 245
		y: 30
		width: 140
		height: 20
		qm_FillRectWidth: 140
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435500
		objId: 268435500
		x: 245
		y: 55
		width: 140
		height: 20
		qm_FillRectWidth: 140
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435499
		objId: 268435499
		x: 245
		y: 80
		width: 140
		height: 20
		qm_FillRectWidth: 140
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435498
		objId: 268435498
		x: 245
		y: 105
		width: 140
		height: 20
		qm_FillRectWidth: 140
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435497
		objId: 268435497
		x: 205
		y: 55
		width: 30
		height: 20
		qm_FillRectWidth: 30
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435496
		objId: 268435496
		x: 205
		y: 80
		width: 30
		height: 20
		qm_FillRectWidth: 30
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435495
		objId: 268435495
		x: 205
		y: 105
		width: 30
		height: 20
		qm_FillRectWidth: 30
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435494
		objId: 268435494
		x: 435
		y: 30
		width: 30
		height: 20
		qm_FillRectWidth: 30
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435493
		objId: 268435493
		x: 435
		y: 55
		width: 30
		height: 20
		qm_FillRectWidth: 30
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435492
		objId: 268435492
		x: 435
		y: 80
		width: 30
		height: 20
		qm_FillRectWidth: 30
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435491
		objId: 268435491
		x: 435
		y: 105
		width: 30
		height: 20
		qm_FillRectWidth: 30
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435490
		objId: 268435490
		x: 0
		y: 0
		width: 480
		height: 25
		qm_FillRectWidth: 480
		qm_FillRectHeight: 25
		qm_FontFamilyName: "Tahoma"
		qm_FontSize: 17
		qm_BorderCornerRadius: 0
		qm_BorderWidth: 1
		qm_BorderColor: "#ff000000"
		qm_ImageID: 17
		qm_TileTop: 2
		qm_TileBottom: 2
		qm_TileRight: 2
		qm_TileLeft: 2
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignTop
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435489
		objId: 268435489
		x: 5
		y: 170
		width: 70
		height: 20
		qm_FillRectWidth: 70
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435488
		objId: 268435488
		x: 10
		y: 210
		width: 70
		height: 20
		qm_FillRectWidth: 70
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435487
		objId: 268435487
		x: 80
		y: 150
		width: 40
		height: 20
		qm_FillRectWidth: 40
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435486
		objId: 268435486
		x: 130
		y: 150
		width: 40
		height: 20
		qm_FillRectWidth: 40
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435485
		objId: 268435485
		x: 180
		y: 150
		width: 40
		height: 20
		qm_FillRectWidth: 40
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435484
		objId: 268435484
		x: 230
		y: 150
		width: 40
		height: 20
		qm_FillRectWidth: 40
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435483
		objId: 268435483
		x: 280
		y: 150
		width: 40
		height: 20
		qm_FillRectWidth: 40
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435482
		objId: 268435482
		x: 330
		y: 150
		width: 40
		height: 20
		qm_FillRectWidth: 40
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435481
		objId: 268435481
		x: 380
		y: 150
		width: 40
		height: 20
		qm_FillRectWidth: 40
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435480
		objId: 268435480
		x: 430
		y: 150
		width: 40
		height: 20
		qm_FillRectWidth: 40
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiIOField
	{
		id: q33554443
		objId: 33554443
		x: 385
		y: 30
		width: 50
		height: 20
		qm_FillRectWidth: 49
		qm_FillRectHeight: 19
		qm_FontSize: 13
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 24
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ffffffff"
		qm_FocusWidth: 0
		qm_FocusColor: "#00000000"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
		qm_passwordMode: false
		qm_FontRendringTpe:1
	}
	IGuiIOField
	{
		id: q33554442
		objId: 33554442
		x: 385
		y: 55
		width: 50
		height: 20
		qm_FillRectWidth: 49
		qm_FillRectHeight: 19
		qm_FontSize: 13
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 24
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ffffffff"
		qm_FocusWidth: 0
		qm_FocusColor: "#00000000"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
		qm_passwordMode: false
		qm_FontRendringTpe:1
	}
	IGuiIOField
	{
		id: q33554441
		objId: 33554441
		x: 385
		y: 80
		width: 50
		height: 20
		qm_FillRectWidth: 49
		qm_FillRectHeight: 19
		qm_FontSize: 13
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 24
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ffffffff"
		qm_FocusWidth: 0
		qm_FocusColor: "#00000000"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
		qm_passwordMode: false
		qm_FontRendringTpe:1
	}
	IGuiIOField
	{
		id: q33554440
		objId: 33554440
		x: 385
		y: 105
		width: 50
		height: 20
		qm_FillRectWidth: 49
		qm_FillRectHeight: 19
		qm_FontSize: 13
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 24
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ffffffff"
		qm_FocusWidth: 0
		qm_FocusColor: "#00000000"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
		qm_passwordMode: false
		qm_FontRendringTpe:1
	}
	IGuiIOField
	{
		id: q33554439
		objId: 33554439
		x: 155
		y: 30
		width: 50
		height: 20
		qm_FillRectWidth: 49
		qm_FillRectHeight: 19
		qm_FontSize: 13
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 24
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ffffffff"
		qm_FocusWidth: 0
		qm_FocusColor: "#00000000"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
		qm_passwordMode: false
		qm_FontRendringTpe:1
	}
	IGuiIOField
	{
		id: q33554438
		objId: 33554438
		x: 155
		y: 55
		width: 50
		height: 20
		qm_FillRectWidth: 49
		qm_FillRectHeight: 19
		qm_FontSize: 13
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 24
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ffffffff"
		qm_FocusWidth: 0
		qm_FocusColor: "#00000000"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
		qm_passwordMode: false
		qm_FontRendringTpe:1
	}
	IGuiIOField
	{
		id: q33554437
		objId: 33554437
		x: 155
		y: 80
		width: 50
		height: 20
		qm_FillRectWidth: 49
		qm_FillRectHeight: 19
		qm_FontSize: 13
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 24
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ffffffff"
		qm_FocusWidth: 0
		qm_FocusColor: "#00000000"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
		qm_passwordMode: false
		qm_FontRendringTpe:1
	}
	IGuiIOField
	{
		id: q33554436
		objId: 33554436
		x: 155
		y: 105
		width: 50
		height: 20
		qm_FillRectWidth: 49
		qm_FillRectHeight: 19
		qm_FontSize: 13
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 24
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ffffffff"
		qm_FocusWidth: 0
		qm_FocusColor: "#00000000"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
		qm_passwordMode: false
		qm_FontRendringTpe:1
	}
	IGuiButton
	{
		id: q486539302
		objId: 486539302
		x: 425
		y: 240
		width: 55
		height: 32
		qm_FillRectWidth: 54
		qm_FillRectHeight: 31
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 22
		qm_TileTop: 15
		qm_TileBottom: 15
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ffffffff"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_FontSize: 13
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
	}
	IGuiButton
	{
		id: q486539301
		objId: 486539301
		x: 0
		y: 240
		width: 55
		height: 32
		qm_FillRectWidth: 54
		qm_FillRectHeight: 31
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 22
		qm_TileTop: 15
		qm_TileBottom: 15
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ffffffff"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_FontSize: 13
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321551
		objId: 352321551
		x: 80
		y: 210
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffceffff"
		qm_SliderRectOnFillColor: "#ff949694"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321550
		objId: 352321550
		x: 130
		y: 210
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffceffff"
		qm_SliderRectOnFillColor: "#ff949694"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321549
		objId: 352321549
		x: 180
		y: 210
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffceffff"
		qm_SliderRectOnFillColor: "#ff949694"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321548
		objId: 352321548
		x: 230
		y: 210
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffceffff"
		qm_SliderRectOnFillColor: "#ff949694"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321547
		objId: 352321547
		x: 280
		y: 210
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffceffff"
		qm_SliderRectOnFillColor: "#ff949694"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321546
		objId: 352321546
		x: 330
		y: 210
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffceffff"
		qm_SliderRectOnFillColor: "#ff949694"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321545
		objId: 352321545
		x: 380
		y: 210
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffceffff"
		qm_SliderRectOnFillColor: "#ff949694"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321544
		objId: 352321544
		x: 430
		y: 210
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffceffff"
		qm_SliderRectOnFillColor: "#ff949694"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321543
		objId: 352321543
		x: 80
		y: 170
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ff00ff00"
		qm_SliderRectOnFillColor: "#ffffff00"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321542
		objId: 352321542
		x: 130
		y: 170
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ff00ff00"
		qm_SliderRectOnFillColor: "#ffffff00"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321541
		objId: 352321541
		x: 180
		y: 170
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ff00ff00"
		qm_SliderRectOnFillColor: "#ffffff00"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321540
		objId: 352321540
		x: 230
		y: 170
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ff00ff00"
		qm_SliderRectOnFillColor: "#ffffff00"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321539
		objId: 352321539
		x: 280
		y: 170
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ff00ff00"
		qm_SliderRectOnFillColor: "#ffffff00"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321538
		objId: 352321538
		x: 330
		y: 170
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ff00ff00"
		qm_SliderRectOnFillColor: "#ffffff00"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321537
		objId: 352321537
		x: 380
		y: 170
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ff00ff00"
		qm_SliderRectOnFillColor: "#ffffff00"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321536
		objId: 352321536
		x: 430
		y: 170
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ff00ff00"
		qm_SliderRectOnFillColor: "#ffffff00"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
}
