import QtQuick 2.0
IGuiPage
{
	id: q16777218
	objId: 16777218
	x: 0
	y: 0
	width: 480
	height: 272
	IGuiContainer
	{
		id: q369098752
		objId: 369098752
		x: 0
		y: 0
		width: 480
		height: 272
	}
	IGuiTextField
	{
		id: q268435540
		objId: 268435540
		x: 0
		y: 130
		width: 480
		height: 105
		qm_FillRectWidth: 479
		qm_FillRectHeight: 104
		qm_FontFamilyName: "Tahoma"
		qm_FontSize: 15
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 1
		qm_BorderColor: "#ff000000"
		qm_ImageID: 20
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignTop
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435539
		objId: 268435539
		x: 0
		y: 0
		width: 480
		height: 25
		qm_FillRectWidth: 480
		qm_FillRectHeight: 25
		qm_FontFamilyName: "Tahoma"
		qm_FontSize: 17
		qm_BorderCornerRadius: 0
		qm_BorderWidth: 1
		qm_BorderColor: "#ff000000"
		qm_ImageID: 17
		qm_TileTop: 2
		qm_TileBottom: 2
		qm_TileRight: 2
		qm_TileLeft: 2
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignTop
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435538
		objId: 268435538
		x: 245
		y: 30
		width: 135
		height: 20
		qm_FillRectWidth: 135
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435537
		objId: 268435537
		x: 245
		y: 55
		width: 135
		height: 20
		qm_FillRectWidth: 135
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435536
		objId: 268435536
		x: 245
		y: 80
		width: 135
		height: 20
		qm_FillRectWidth: 135
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435535
		objId: 268435535
		x: 205
		y: 55
		width: 30
		height: 20
		qm_FillRectWidth: 30
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435534
		objId: 268435534
		x: 205
		y: 80
		width: 30
		height: 20
		qm_FillRectWidth: 30
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435533
		objId: 268435533
		x: 205
		y: 105
		width: 30
		height: 20
		qm_FillRectWidth: 30
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435532
		objId: 268435532
		x: 435
		y: 30
		width: 30
		height: 20
		qm_FillRectWidth: 30
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435531
		objId: 268435531
		x: 435
		y: 55
		width: 30
		height: 20
		qm_FillRectWidth: 30
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435530
		objId: 268435530
		x: 435
		y: 80
		width: 30
		height: 20
		qm_FillRectWidth: 30
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435529
		objId: 268435529
		x: 435
		y: 105
		width: 30
		height: 20
		qm_FillRectWidth: 30
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435528
		objId: 268435528
		x: 5
		y: 170
		width: 70
		height: 20
		qm_FillRectWidth: 70
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435527
		objId: 268435527
		x: 245
		y: 105
		width: 135
		height: 20
		qm_FillRectWidth: 135
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435526
		objId: 268435526
		x: 80
		y: 150
		width: 40
		height: 20
		qm_FillRectWidth: 40
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435525
		objId: 268435525
		x: 130
		y: 150
		width: 40
		height: 20
		qm_FillRectWidth: 40
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435524
		objId: 268435524
		x: 180
		y: 150
		width: 40
		height: 20
		qm_FillRectWidth: 40
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435523
		objId: 268435523
		x: 230
		y: 150
		width: 40
		height: 20
		qm_FillRectWidth: 40
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435522
		objId: 268435522
		x: 280
		y: 150
		width: 40
		height: 20
		qm_FillRectWidth: 40
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435521
		objId: 268435521
		x: 330
		y: 150
		width: 40
		height: 20
		qm_FillRectWidth: 40
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435520
		objId: 268435520
		x: 380
		y: 150
		width: 40
		height: 20
		qm_FillRectWidth: 40
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435519
		objId: 268435519
		x: 430
		y: 150
		width: 40
		height: 20
		qm_FillRectWidth: 40
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435518
		objId: 268435518
		x: 15
		y: 30
		width: 135
		height: 20
		qm_FillRectWidth: 135
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435517
		objId: 268435517
		x: 205
		y: 30
		width: 30
		height: 20
		qm_FillRectWidth: 30
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435516
		objId: 268435516
		x: 15
		y: 55
		width: 135
		height: 20
		qm_FillRectWidth: 135
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435515
		objId: 268435515
		x: 15
		y: 80
		width: 135
		height: 20
		qm_FillRectWidth: 135
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435514
		objId: 268435514
		x: 15
		y: 105
		width: 135
		height: 20
		qm_FillRectWidth: 135
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiTextField
	{
		id: q268435513
		objId: 268435513
		x: 10
		y: 210
		width: 70
		height: 20
		qm_FillRectWidth: 70
		qm_FillRectHeight: 20
		qm_FontFamilyName: "Tahoma"
		qm_FontSize: 13
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 0
		qm_BorderColor: "#ff424952"
		qm_ImageID: 18
		qm_TileTop: 0
		qm_TileBottom: 0
		qm_TileRight: 0
		qm_TileLeft: 0
		qm_Transparent : true 
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignLeft
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
	}
	IGuiIOField
	{
		id: q33554462
		objId: 33554462
		x: 155
		y: 30
		width: 50
		height: 20
		qm_FillRectWidth: 49
		qm_FillRectHeight: 19
		qm_FontSize: 13
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 24
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ffffffff"
		qm_FocusWidth: 0
		qm_FocusColor: "#00000000"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
		qm_passwordMode: false
		qm_FontRendringTpe:1
	}
	IGuiIOField
	{
		id: q33554461
		objId: 33554461
		x: 155
		y: 55
		width: 50
		height: 20
		qm_FillRectWidth: 49
		qm_FillRectHeight: 19
		qm_FontSize: 13
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 24
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ffffffff"
		qm_FocusWidth: 0
		qm_FocusColor: "#00000000"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
		qm_passwordMode: false
		qm_FontRendringTpe:1
	}
	IGuiIOField
	{
		id: q33554460
		objId: 33554460
		x: 155
		y: 80
		width: 50
		height: 20
		qm_FillRectWidth: 49
		qm_FillRectHeight: 19
		qm_FontSize: 13
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 24
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ffffffff"
		qm_FocusWidth: 0
		qm_FocusColor: "#00000000"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
		qm_passwordMode: false
		qm_FontRendringTpe:1
	}
	IGuiIOField
	{
		id: q33554459
		objId: 33554459
		x: 155
		y: 105
		width: 50
		height: 20
		qm_FillRectWidth: 49
		qm_FillRectHeight: 19
		qm_FontSize: 13
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 24
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ffffffff"
		qm_FocusWidth: 0
		qm_FocusColor: "#00000000"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
		qm_passwordMode: false
		qm_FontRendringTpe:1
	}
	IGuiIOField
	{
		id: q33554458
		objId: 33554458
		x: 385
		y: 30
		width: 50
		height: 20
		qm_FillRectWidth: 49
		qm_FillRectHeight: 19
		qm_FontSize: 13
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 24
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ffffffff"
		qm_FocusWidth: 0
		qm_FocusColor: "#00000000"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
		qm_passwordMode: false
		qm_FontRendringTpe:1
	}
	IGuiIOField
	{
		id: q33554457
		objId: 33554457
		x: 385
		y: 55
		width: 50
		height: 20
		qm_FillRectWidth: 49
		qm_FillRectHeight: 19
		qm_FontSize: 13
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 24
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ffffffff"
		qm_FocusWidth: 0
		qm_FocusColor: "#00000000"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
		qm_passwordMode: false
		qm_FontRendringTpe:1
	}
	IGuiIOField
	{
		id: q33554456
		objId: 33554456
		x: 385
		y: 80
		width: 50
		height: 20
		qm_FillRectWidth: 49
		qm_FillRectHeight: 19
		qm_FontSize: 13
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 24
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ffffffff"
		qm_FocusWidth: 0
		qm_FocusColor: "#00000000"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
		qm_passwordMode: false
		qm_FontRendringTpe:1
	}
	IGuiIOField
	{
		id: q33554455
		objId: 33554455
		x: 385
		y: 105
		width: 50
		height: 20
		qm_FillRectWidth: 49
		qm_FillRectHeight: 19
		qm_FontSize: 13
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 24
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ffffffff"
		qm_FocusWidth: 0
		qm_FocusColor: "#00000000"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 3
		qm_MarginRight: 2
		qm_MarginBottom: 2
		qm_MarginTop: 2
		qm_passwordMode: false
		qm_FontRendringTpe:1
	}
	IGuiButton
	{
		id: q486539309
		objId: 486539309
		x: 425
		y: 240
		width: 55
		height: 32
		qm_FillRectWidth: 54
		qm_FillRectHeight: 31
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 22
		qm_TileTop: 15
		qm_TileBottom: 15
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ffffffff"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_FontSize: 13
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
	}
	IGuiButton
	{
		id: q486539308
		objId: 486539308
		x: 0
		y: 240
		width: 55
		height: 32
		qm_FillRectWidth: 54
		qm_FillRectHeight: 31
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 22
		qm_TileTop: 15
		qm_TileBottom: 15
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ffffffff"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_FontSize: 13
		qm_FontFamilyName: "Tahoma"
		qm_FontBold: true
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321567
		objId: 352321567
		x: 80
		y: 170
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ff00ff00"
		qm_SliderRectOnFillColor: "#ffffff00"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321566
		objId: 352321566
		x: 130
		y: 170
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ff00ff00"
		qm_SliderRectOnFillColor: "#ffffff00"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321565
		objId: 352321565
		x: 180
		y: 170
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ff00ff00"
		qm_SliderRectOnFillColor: "#ffffff00"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321564
		objId: 352321564
		x: 230
		y: 170
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ff00ff00"
		qm_SliderRectOnFillColor: "#ffffff00"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321563
		objId: 352321563
		x: 280
		y: 170
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ff00ff00"
		qm_SliderRectOnFillColor: "#ffffff00"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321562
		objId: 352321562
		x: 330
		y: 170
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ff00ff00"
		qm_SliderRectOnFillColor: "#ffffff00"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321561
		objId: 352321561
		x: 380
		y: 170
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ff00ff00"
		qm_SliderRectOnFillColor: "#ffffff00"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321560
		objId: 352321560
		x: 430
		y: 170
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ff00ff00"
		qm_SliderRectOnFillColor: "#ffffff00"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321559
		objId: 352321559
		x: 80
		y: 210
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffceffff"
		qm_SliderRectOnFillColor: "#ff949694"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321558
		objId: 352321558
		x: 130
		y: 210
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffceffff"
		qm_SliderRectOnFillColor: "#ff949694"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321557
		objId: 352321557
		x: 180
		y: 210
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffceffff"
		qm_SliderRectOnFillColor: "#ff949694"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321556
		objId: 352321556
		x: 230
		y: 210
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffceffff"
		qm_SliderRectOnFillColor: "#ff949694"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321555
		objId: 352321555
		x: 280
		y: 210
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffceffff"
		qm_SliderRectOnFillColor: "#ff949694"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321554
		objId: 352321554
		x: 330
		y: 210
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffceffff"
		qm_SliderRectOnFillColor: "#ff949694"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321553
		objId: 352321553
		x: 380
		y: 210
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffceffff"
		qm_SliderRectOnFillColor: "#ff949694"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
	IGuiSliderSwitchHorizontal
	{
		id: q352321552
		objId: 352321552
		x: 430
		y: 210
		width: 40
		height: 20
		qm_FillRectWidth: 39
		qm_FillRectHeight: 19
		qm_BorderCornerRadius: 3
		qm_BorderWidth: 2
		qm_BorderColor: "#ff000000"
		qm_ImageID: 21
		qm_TileTop: 5
		qm_TileBottom: 5
		qm_TileRight: 5
		qm_TileLeft: 5
		qm_FillColor: "#ff636573"
		qm_TextColor: "#ff000000"
		qm_ValueVarTextAlignmentHorizontal: Text.AlignHCenter
		qm_ValueVarTextAlignmentVertical: Text.AlignVCenter
		qm_ValueVarTextOrientation: 0
		qm_MarginLeft: 0
		qm_MarginRight: 0
		qm_MarginBottom: 0
		qm_MarginTop: 0
		qm_FocusWidth: 2
		qm_FocusColor: "#ff94b6e7"
		qm_SliderRectHeight: 19
		qm_SliderRectWidth: 19
		qm_SliderRectBorderCornerRadius: 3
		qm_SliderRectBorderWidth: 2
		qm_SliderRectImageID: 22
		qm_SliderRectTileTop: 10
		qm_SliderRectTileBottom: 10
		qm_SliderRectTileRight: 5
		qm_SliderRectTileLeft: 5
		qm_SliderGripBorderCornerRadius: 3
		qm_SliderGripBorderWidth: 2
		qm_SliderGripImageID: 23
		qm_SliderGripTileWidth: 8
		qm_SliderGripTileHeight: 56
		qm_SliderGripTileTop: 10
		qm_SliderGripTileBottom: 10
		qm_SliderGripTileRight: 0
		qm_SliderGripTileLeft: 0
		qm_SliderRectOffFillColor: "#ffceffff"
		qm_SliderRectOnFillColor: "#ff949694"
		qm_FontSize: 9
		qm_FontFamilyName: "Tahoma"
		qm_SwichOnSide: true
		qm_SwitchOnValue: 1
	}
}
